package accounts

import (
	"bytes"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/vlxlv/agy-go/internal/storage"
)

func TestCrypto_DecryptPythonVector(t *testing.T) {
	// Fixed vector generated by Python agy-pool
	vectorJSON := `{
		"format": "agy-pool-encrypted-v1",
		"kdf": "pbkdf2_hmac_sha256",
		"iterations": 100000,
		"salt": "MLkMXv+/FTjdr+5c0kMZpQ==",
		"nonce": "v+CaGz1x+PYSeUmb3hbJTA==",
		"ciphertext": "b3sQxoW7crJPmgTptQLidIgYI7vSO6xVvA/daUk6kzXF",
		"tag": "jmRYdMWlTvDn4mSb34svuPJOOiR2eBCTvLUjxlpbSR4="
	}`
	password := "test-pass-phrase-42"
	expectedPlaintext := "hello agy-pool encrypted test 123"

	var bundle EncryptedBundle
	if err := json.Unmarshal([]byte(vectorJSON), &bundle); err != nil {
		t.Fatalf("failed to unmarshal bundle: %v", err)
	}

	decrypted, err := DecryptBundle(&bundle, password)
	if err != nil {
		t.Fatalf("DecryptBundle failed on Python vector: %v", err)
	}

	if string(decrypted) != expectedPlaintext {
		t.Fatalf("decrypted = %q, want %q", string(decrypted), expectedPlaintext)
	}
}

func TestCrypto_RejectsExcessivePBKDF2Work(t *testing.T) {
	bundle := &EncryptedBundle{
		Format:     "agy-pool-encrypted-v1",
		Iterations: maxPBKDF2Iterations + 1,
	}
	if _, err := DecryptBundle(bundle, "password"); err == nil {
		t.Fatal("expected excessive PBKDF2 iterations to be rejected")
	}
}

func TestCrypto_CrossLanguageRoundtrip(t *testing.T) {
	plaintext := []byte("cross-language-verification-42-secret-payload")
	password := "super-secure-passphrase"

	// Encrypt in Go
	bundle, err := EncryptBundle(plaintext, password, nil, nil)
	if err != nil {
		t.Fatalf("EncryptBundle failed: %v", err)
	}

	// Decrypt in Go
	decryptedGo, err := DecryptBundle(bundle, password)
	if err != nil {
		t.Fatalf("DecryptBundle in Go failed: %v", err)
	}
	if !bytes.Equal(decryptedGo, plaintext) {
		t.Fatalf("Go self-roundtrip failed: got %q, want %q", decryptedGo, plaintext)
	}

	// Verify Python can decrypt Go's bundle if python3 and Python reference repo are available
	pythonPath, err := exec.LookPath("python3")
	if err != nil {
		t.Skip("python3 not found, skipping Python cross-check")
	}

	pyRepo := os.Getenv("PYTHON_REFERENCE")
	if pyRepo == "" {
		pyRepo = os.Getenv("AGY_PYTHON_ROOT")
	}
	if pyRepo == "" {
		cand := "/home/codex/agy-pool"
		if st, err := os.Stat(cand); err == nil && st.IsDir() {
			pyRepo = cand
		}
	}
	if pyRepo == "" {
		t.Skip("Python reference repository not found, skipping live cross-check")
	}
	if st, err := os.Stat(pyRepo); err != nil || !st.IsDir() {
		t.Skip("Python reference repository not found, skipping live cross-check")
	}

	bundleBytes, err := json.Marshal(bundle)
	if err != nil {
		t.Fatalf("failed to marshal bundle: %v", err)
	}

	cmd := exec.Command(pythonPath, "-c", `
import sys, json
from agy_pool.accounts import decrypt_bundle

bundle = json.loads(sys.argv[1])
pw = sys.argv[2]
plaintext = decrypt_bundle(bundle, pw)
sys.stdout.write(plaintext.decode("utf-8"))
`, string(bundleBytes), password)

	// Set PYTHONPATH to repo root to find agy_pool
	cmd.Env = append(os.Environ(), "PYTHONPATH="+pyRepo)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("Python failed to decrypt Go bundle: %v, output: %s", err, string(out))
	}

	if string(out) != string(plaintext) {
		t.Fatalf("Python decrypted %q, want %q", string(out), string(plaintext))
	}
}

func TestCrypto_TamperResistance(t *testing.T) {
	plaintext := []byte("secret data")
	password := "correct-password"

	bundle, err := EncryptBundle(plaintext, password, nil, nil)
	if err != nil {
		t.Fatalf("EncryptBundle failed: %v", err)
	}

	// Wrong password
	if _, err := DecryptBundle(bundle, "wrong-password"); err == nil {
		t.Fatal("expected error on wrong password")
	}

	// Wrong format
	corruptFormat := *bundle
	corruptFormat.Format = "unknown-format"
	if _, err := DecryptBundle(&corruptFormat, password); err == nil {
		t.Fatal("expected error on invalid format")
	}

	// Corrupted tag
	corruptTag := *bundle
	corruptTag.Tag = "AAAA" + corruptTag.Tag[4:]
	if _, err := DecryptBundle(&corruptTag, password); err == nil {
		t.Fatal("expected error on corrupted tag")
	}

	// Corrupted ciphertext
	corruptCipher := *bundle
	corruptCipher.Ciphertext = "AAAA" + corruptCipher.Ciphertext[4:]
	if _, err := DecryptBundle(&corruptCipher, password); err == nil {
		t.Fatal("expected error on corrupted ciphertext")
	}
}

func TestExportAndImportPool(t *testing.T) {
	tmp := setupIsolatedTestDir(t)

	pool := storage.NewEmptyPool()
	pool.Strategy = "round_robin"
	acc1 := &storage.Account{
		ID:           "acc_1",
		Email:        "user1@gmail.com",
		RefreshToken: "rf_1",
		AccessToken:  "at_1",
	}
	acc2 := &storage.Account{
		ID:           "acc_2",
		Email:        "user2@gmail.com",
		RefreshToken: "rf_2",
		AccessToken:  "at_2",
	}
	pool.Accounts = []*storage.Account{acc1, acc2}
	pool.ActiveAccountID = &acc1.ID
	if err := storage.SavePool(pool); err != nil {
		t.Fatalf("failed to save pool: %v", err)
	}

	plainExportPath := filepath.Join(tmp, "export-plain.json")
	outPath, err := ExportPool(plainExportPath, false, "", false)
	if err != nil {
		t.Fatalf("ExportPool plain failed: %v", err)
	}
	if outPath != plainExportPath {
		t.Fatalf("got path %q, want %q", outPath, plainExportPath)
	}

	// Verify file mode 0600
	info, err := os.Stat(plainExportPath)
	if err != nil {
		t.Fatalf("stat failed: %v", err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Fatalf("export file perm = %o, want 0600", info.Mode().Perm())
	}

	// Test Encrypted Export
	encExportPath := filepath.Join(tmp, "export-enc.enc")
	_, err = ExportPool(encExportPath, true, "secret123", false)
	if err != nil {
		t.Fatalf("ExportPool encrypted failed: %v", err)
	}

	// Clear pool to test import with replace
	if err := storage.SavePool(storage.NewEmptyPool()); err != nil {
		t.Fatalf("failed to reset pool: %v", err)
	}

	// Import encrypted backup
	res, err := ImportPool(encExportPath, "secret123", true, false)
	if err != nil {
		t.Fatalf("ImportPool encrypted failed: %v", err)
	}
	if res.Added != 2 || res.Total != 2 {
		t.Fatalf("unexpected import result: %+v", res)
	}

	loaded, _ := storage.LoadPool()
	if loaded.Strategy != "round_robin" {
		t.Fatalf("strategy not restored: %q", loaded.Strategy)
	}
	if len(loaded.Accounts) != 2 {
		t.Fatalf("expected 2 accounts restored, got %d", len(loaded.Accounts))
	}
	if loaded.Accounts[0].Email != "user1@gmail.com" || loaded.Accounts[1].Email != "user2@gmail.com" {
		t.Fatalf("restored accounts mismatch: %+v", loaded.Accounts)
	}

	// Test Import Merge: update user1 with new access token, add user3
	newBackupPath := filepath.Join(tmp, "update-backup.json")
	newBundle := map[string]any{
		"version": 1,
		"accounts": []map[string]any{
			{
				"email":         "user1@gmail.com",
				"refresh_token": "rf_1_new",
				"access_token":  "at_1_new",
			},
			{
				"email":         "user3@gmail.com",
				"refresh_token": "rf_3",
				"access_token":  "at_3",
			},
		},
	}
	data, _ := json.Marshal(newBundle)
	_ = os.WriteFile(newBackupPath, data, 0o600)

	mergeRes, err := ImportPool(newBackupPath, "", false, false)
	if err != nil {
		t.Fatalf("ImportPool merge failed: %v", err)
	}
	if mergeRes.Added != 1 || mergeRes.Updated != 1 || mergeRes.Total != 3 {
		t.Fatalf("merge result mismatch: %+v", mergeRes)
	}

	loadedAfterMerge, _ := storage.LoadPool()
	acc1Updated := FindAccountByTarget(loadedAfterMerge.Accounts, "user1@gmail.com")
	if acc1Updated == nil || acc1Updated.RefreshToken != "rf_1_new" || acc1Updated.AccessToken != "at_1_new" {
		t.Fatalf("user1 not updated properly: %+v", acc1Updated)
	}
	acc3Added := FindAccountByTarget(loadedAfterMerge.Accounts, "user3@gmail.com")
	if acc3Added == nil || acc3Added.ID != "acc_3" {
		t.Fatalf("user3 not added properly: %+v", acc3Added)
	}

	// Test skipExisting
	skipRes, err := ImportPool(newBackupPath, "", false, true)
	if err != nil {
		t.Fatalf("ImportPool skipExisting failed: %v", err)
	}
	if skipRes.Skipped != 2 || skipRes.Added != 0 || skipRes.Updated != 0 {
		t.Fatalf("skipExisting result mismatch: %+v", skipRes)
	}
}
